instructors:
  - id: 1
    name: "John Doe"
    email: "email-of-the-instructor@gmail.com"

# To save instructors' effort, we do not assign the same feedback request to multiple instructors.
# However, if a feedback request is shown to one instructor but not processed within the timeout period, it can be reassigned.
# The argument `feedback_timeout` specifies the duration (in minutes) after which a feedback request can be reassigned.
feedback_timeout: 30

# Email configuration:
# Format the notification emails sent to instructors when a feedback request is created or updated.
instructor_notification_email:
  subject: "Feedback Service Update: {n_unprocessed_requests} unprocessed requests, {n_inprocessing_requests} requests in processing"
  body: |-
    Hello,

    There is a change in the number of requests in the feedback service.

    Currently, there are {n_unprocessed_requests} unprocessed requests and {n_inprocessing_requests} requests in processing.

    Please check the feedback service dashboard for more details.

    Best,
    Email is automatically generated by the Feedback Team

# Format the notification emails sent to students when feedback is available.
student_notification_email:
  subject: "Feedback from an instructor for {problem_id} is available"
  body: |-
    Hello,

    Feedback from an instructor for {problem_id} is now available.

    Please check the platform to view the feedback.

    Best,
    Email is automatically generated by the Feedback Team